import type { GoalDefinition } from './types';

export const DEFAULT_GOAL_DEFINITIONS: GoalDefinition[] = [
  {
    id: 'dream-car',
    type: 'financial',
    title: 'Dream car',
    category: 'financial',
    description: 'Save for a 2025 model with cash so expenses stay predictable.',
    baseline: 0,
    target: 5_000_000,
    unit: 'UZS',
    currency: 'UZS',
    cadence: 'monthly',
    deadline: '2025-03-31',
    pacingWindowDays: 90,
    sources: { finance: true, manual: true },
    tracks: [
      {
        id: 'dream-car-fund',
        type: 'money',
        target: 5_000_000,
        unit: 'UZS',
        currency: 'UZS',
      },
    ],
  },
  {
    id: 'emergency-fund',
    type: 'financial',
    title: 'Emergency fund',
    category: 'financial',
    baseline: 0,
    target: 6_000_000,
    unit: 'UZS',
    currency: 'UZS',
    cadence: 'monthly',
    deadline: '2025-06-30',
    pacingWindowDays: 120,
    sources: { finance: true, manual: true },
    tracks: [
      {
        id: 'emergency-pool',
        type: 'money',
        target: 6_000_000,
        unit: 'UZS',
        currency: 'UZS',
      },
    ],
  },
  {
    id: 'fitness',
    type: 'quantitative',
    title: 'Peak fitness plan',
    category: 'health',
    baseline: 0,
    target: 210,
    unit: 'sessions',
    cadence: 'weekly',
    pacingWindowDays: 45,
    sources: { tasks: true, habits: true, manual: true },
    tracks: [
      {
        id: 'fitness-sessions',
        type: 'tasks',
        target: 210,
        unit: 'sessions',
        scope: 'count',
        weight: 0.7,
      },
      {
        id: 'fitness-streak',
        type: 'streak',
        target: 5,
        unit: 'days',
        cadence: 'weekly',
        targetDays: 5,
        graceDays: 1,
        weight: 0.3,
      },
    ],
  },
  {
    id: 'language',
    type: 'skill',
    title: 'Spanish language immersion',
    category: 'education',
    baseline: 0,
    target: 50,
    unit: 'lessons',
    cadence: 'weekly',
    pacingWindowDays: 60,
    sources: { tasks: true, habits: true, focus: true, manual: true },
    tracks: [
      {
        id: 'language-lessons',
        type: 'tasks',
        target: 50,
        unit: 'lessons',
        scope: 'count',
        weight: 0.5,
      },
      {
        id: 'language-focus',
        type: 'time',
        target: 300,
        unit: 'minutes',
        cadence: 'weekly',
        minutesPerUnit: 1,
        xpRatio: 0.2,
        weight: 0.2,
      },
      {
        id: 'language-milestones',
        type: 'milestone',
        target: 5,
        unit: 'milestones',
        weight: 0.3,
        milestones: [
          { id: 'spanish-a1', title: 'Pass A1 exam', weight: 1 },
          { id: 'spanish-500-words', title: 'Learn 500 words', weight: 1 },
          { id: 'spanish-30-lessons', title: 'Finish 30 tutor lessons', weight: 1 },
          { id: 'spanish-a2-grammar', title: 'Master A2 grammar set', weight: 1 },
          { id: 'spanish-final', title: 'Complete A2 mock exam', weight: 1 },
        ],
      },
    ],
  },
];
