import { useCallback, useMemo } from 'react';

import { useSettingsStore } from '@/stores/useSettingsStore';

type LocaleCode = 'en' | 'ru' | 'uz';

const translations: Record<LocaleCode, Record<string, string>> = {
  en: {
    'finance.incomeOutcomeTitle': 'Income & Outcome',
    'finance.incomeSubtitle': 'Track money that comes into your accounts',
    'finance.outcomeSubtitle': 'Track expenses with detailed categories',
    'finance.income': 'Income',
    'finance.outcome': 'Outcome',
    'finance.amount': 'Amount',
    'finance.category': 'Category',
    'finance.account': 'Account',
    'finance.date': 'Date',
    'finance.note': 'Note',
    'finance.notePlaceholder': 'Add optional description or context…',
    'finance.addEntry': 'Save Entry',
    'finance.saveChanges': 'Save Changes',
    'finance.changeDate': 'Change date',
    'finance.selectAccount': 'Select account',
    'finance.selectAccountPlaceholder': 'Select an account',
    'finance.addCategory': 'Add category',
    'finance.editCategory': 'Edit category',
    'finance.categoryPlaceholder': 'Category name',
    'finance.save': 'Save',
    'finance.selectDate': 'Select date',
    'finance.transferTitle': 'Transfer between accounts',
    'finance.transferSubtitle': 'Move money securely across wallets',
    'finance.fromAccount': 'From account',
    'finance.toAccount': 'To account',
    'finance.select': 'Select',
    'finance.balanceUnavailable': 'Balance unavailable',
    'finance.transfer': 'Transfer',
    'finance.selectFromAccount': 'Select source account',
    'finance.selectToAccount': 'Select destination account',
    'finance.debtTitle': 'Debt & Loans',
    'finance.debtSubtitle': 'Track money borrowed or lent with clarity',
    'finance.debtStatusLent': 'You lent money',
    'finance.debtStatusBorrowed': 'You borrowed money',
    'finance.borrowed': 'Borrowed',
    'finance.lent': 'Lent',
    'finance.person': 'Name / Person',
    'finance.personPlaceholder': 'Who is this debt for?',
    'finance.expectedReturn': 'Expected return date',
    'finance.selectDateHint': 'Pick a date',
    'finance.clear': 'Clear',
    'finance.expectedPlaceholder': 'No return date set',
  },
  ru: {
    'finance.incomeOutcomeTitle': 'Доходы и расходы',
    'finance.incomeSubtitle': 'Фиксируйте поступления на ваши счета',
    'finance.outcomeSubtitle': 'Отслеживайте расходы по категориям',
    'finance.income': 'Доход',
    'finance.outcome': 'Расход',
    'finance.amount': 'Сумма',
    'finance.category': 'Категория',
    'finance.account': 'Счёт',
    'finance.date': 'Дата',
    'finance.note': 'Заметка',
    'finance.notePlaceholder': 'Добавьте описание или детали…',
    'finance.addEntry': 'Сохранить запись',
    'finance.saveChanges': 'Сохранить изменения',
    'finance.changeDate': 'Изменить дату',
    'finance.selectAccount': 'Выбрать счёт',
    'finance.selectAccountPlaceholder': 'Выберите счёт',
    'finance.addCategory': 'Новая категория',
    'finance.editCategory': 'Редактировать категорию',
    'finance.categoryPlaceholder': 'Название категории',
    'finance.save': 'Сохранить',
    'finance.selectDate': 'Выберите дату',
    'finance.transferTitle': 'Перевод между счетами',
    'finance.transferSubtitle': 'Перемещайте средства между кошельками',
    'finance.fromAccount': 'Со счёта',
    'finance.toAccount': 'На счёт',
    'finance.select': 'Выбрать',
    'finance.balanceUnavailable': 'Баланс недоступен',
    'finance.transfer': 'Перевести',
    'finance.selectFromAccount': 'Выберите исходный счёт',
    'finance.selectToAccount': 'Выберите целевой счёт',
    'finance.debtTitle': 'Долги и займы',
    'finance.debtSubtitle': 'Отслеживайте занятые и одолженные суммы',
    'finance.debtStatusLent': 'Вы одолжили деньги',
    'finance.debtStatusBorrowed': 'Вы заняли деньги',
    'finance.borrowed': 'Я занял',
    'finance.lent': 'Я дал',
    'finance.person': 'Имя / Человек',
    'finance.personPlaceholder': 'Для кого этот долг?',
    'finance.expectedReturn': 'Ожидаемая дата возврата',
    'finance.selectDateHint': 'Выберите дату',
    'finance.clear': 'Очистить',
    'finance.expectedPlaceholder': 'Дата возврата не установлена',
  },
  uz: {
    'finance.incomeOutcomeTitle': 'Daromad va xarajatlar',
    'finance.incomeSubtitle': 'Hisoblaringizga tushgan mablag‘larni qayd eting',
    'finance.outcomeSubtitle': 'Xarajatlarni kategoriyalar bo‘yicha kuzating',
    'finance.income': 'Daromad',
    'finance.outcome': 'Xarajat',
    'finance.amount': 'Summasi',
    'finance.category': 'Kategoriya',
    'finance.account': 'Hisob',
    'finance.date': 'Sana',
    'finance.note': 'Izoh',
    'finance.notePlaceholder': 'Qo‘shimcha izoh yoki tafsilot kiriting…',
    'finance.addEntry': 'Yozuvni saqlash',
    'finance.saveChanges': 'O‘zgartirishlarni saqlash',
    'finance.changeDate': 'Sanani o‘zgartirish',
    'finance.selectAccount': 'Hisobni tanlang',
    'finance.selectAccountPlaceholder': 'Hisobni tanlang',
    'finance.addCategory': 'Yangi kategoriya',
    'finance.editCategory': 'Kategoriyani tahrirlash',
    'finance.categoryPlaceholder': 'Kategoriya nomi',
    'finance.save': 'Saqlash',
    'finance.selectDate': 'Sanani tanlang',
    'finance.transferTitle': 'Hisoblar o‘rtasida o‘tkazma',
    'finance.transferSubtitle': 'Pulni xavfsiz tarzda hamyonlar o‘rtasida ko‘chiring',
    'finance.fromAccount': 'Qaysi hisobdan',
    'finance.toAccount': 'Qaysi hisoblarga',
    'finance.select': 'Tanlang',
    'finance.balanceUnavailable': 'Balans mavjud emas',
    'finance.transfer': 'O‘tkazish',
    'finance.selectFromAccount': 'Manba hisobni tanlang',
    'finance.selectToAccount': 'Qabul qiluvchi hisobni tanlang',
    'finance.debtTitle': 'Qarz va ssudalar',
    'finance.debtSubtitle': 'Olingan yoki berilgan mablag‘larni nazorat qiling',
    'finance.debtStatusLent': 'Siz qarz berdingiz',
    'finance.debtStatusBorrowed': 'Siz qarz oldingiz',
    'finance.borrowed': 'Qarz oldim',
    'finance.lent': 'Qarz berdim',
    'finance.person': 'Ism / Shaxs',
    'finance.personPlaceholder': 'Bu qarz kim uchun?',
    'finance.expectedReturn': 'Qaytarish sanasi',
    'finance.selectDateHint': 'Sanani tanlang',
    'finance.clear': 'Bekor qilish',
    'finance.expectedPlaceholder': 'Qaytarish sanasi belgilanmagan',
  },
};

const FALLBACK_LOCALE: LocaleCode = 'en';

export const useTranslation = () => {
  const language = useSettingsStore((state) => state.language) as LocaleCode;

  const dictionary = useMemo(() => translations[language] ?? translations[FALLBACK_LOCALE], [
    language,
  ]);

  const t = useCallback(
    (key: string) => dictionary[key] ?? translations[FALLBACK_LOCALE][key] ?? key,
    [dictionary]
  );

  return { t, language: language ?? FALLBACK_LOCALE };
};
